name: grindworks
description: Platform Aplikasi Pencari Kerja Bidang Digital
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  dots_indicator: ^3.0.0
  http: ^1.2.1
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background1.png

    
